import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { TbBrandGithub } from 'react-icons/tb'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Corpspace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
  
        <div className={styles.center}>
          <h1 style={{marginRight: '1rem'}}>We are in</h1>
          <a href='https://github.com/sulsoltanoff/corpspace' className={styles.github} style={{margin: '-0.5rem 0'}}>
            <TbBrandGithub size="40"/>
          </a>
          <h1 style={{marginLeft: '1rem'}}>Development</h1>
        </div>

      </main>
    </>
  )
}
